# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Kyle A. Novak
title: mathematician ▪ data scientist ▪ decision analyst
email: "kylenovak29@gmail.com"
url: "https://kylenovak29.github.io"

# Social links
twitter_username: kylenovak29
github_username:  kylenovak29
linkedin_username: kylenovak29
#youtube_username: kylenovak29

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: "https://raw.githubusercontent.com/kylenovak29/documents/master/Kyle_Novak_Cartoon_G.png"
      
about_content: | # this will include new lines to allow paragraphs
  I am an applied mathematician with over twenty-two years of research and analysis experience. I nerd out on data science and data communication. My goal is to make a better world by improving science-based, data-informed decision making.

  As an applied mathematician, I have a broad background in developing mathematical and computer modeling in fluid dynamics, quantum mechanics, nanotechnology, superconductors, biology, aeronautics, air base resiliency, and cryptography. I have co-authored several research articles and taught graduate and undergraduate mathematics.

  As a data scientist, I have experience in machine learning algorithms, specialized data visualization, statistical analysis, operations research, design of experiment, and network analysis. More importantly, I have experience leading and mentoring analysts to produce timely, impactful results.

  As a decision analyst, I have worked at four military headquarters across the world where I helped executive leaders make better, objective decisions. I have experience translating analysis to actionable policy and communicating it to senior leaders. I have conducted lessons learned and process evaluation, led collaborative and integrated product teams, and conducted strategic assessments.

# Projects Section
# projects_title: Publications #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about experience section title)
  


## More Section
## more_title: A Little More About Me #(Use this to override about more section title)
#more_content: | # this will include new lines to allow paragraphs
#  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#
#  Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
